#!/usr/bin/env bash
# Builds the secret-bearing runtime env file for Compose from the user-supplied inputs.
#   input : ~/.config/easytrade-otel-lab/lab.json, ~/.config/easytrade-otel-lab/dynatrace-platform-token
#   output: ~/.config/easytrade-otel-lab/otel.env  (mode 0600, outside the checkout, never printed)
set -euo pipefail
CFG="${EASYTRADE_LAB_CONFIG_DIR:-$HOME/.config/easytrade-otel-lab}"
LAB_JSON="$CFG/lab.json"; TOKEN_FILE="$CFG/dynatrace-platform-token"; OUT="$CFG/otel.env"
[ -r "$LAB_JSON" ] || { echo "missing $LAB_JSON" >&2; exit 2; }
[ -r "$TOKEN_FILE" ] || { echo "missing $TOKEN_FILE" >&2; exit 2; }
ENDPOINT="$(jq -r '.otlp_endpoint' "$LAB_JSON")"
[ -n "$ENDPOINT" ] && [ "$ENDPOINT" != null ] || { echo "otlp_endpoint missing in $LAB_JSON" >&2; exit 2; }
ENDPOINT="${ENDPOINT%/}"
TOKEN="$(tr -d '\r\n' < "$TOKEN_FILE")"
[ -n "$TOKEN" ] || { echo "token file is empty" >&2; exit 2; }
umask 077
tmp="$(mktemp "$CFG/.otel.env.XXXXXX")"
{
  echo "# generated by otel-lab/scripts/gen-runtime-env.sh - contains a secret, never commit"
  echo "OTEL_EXPORTER_OTLP_ENDPOINT=$ENDPOINT"
  echo "OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer $TOKEN"
} > "$tmp"
mv "$tmp" "$OUT"; chmod 0600 "$OUT"
echo "wrote $OUT (endpoint $ENDPOINT, token length ${#TOKEN})"
